name: Update foundry-bin daily

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *' # Run daily

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Building package
        run: 'cd ./foundry-bin && ./update.sh nightly'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'foundry-bin/releases.nix: Nightly update'
          commit_author: Nix Updater <actions@github.com>
