name: Update foundry-bin rc

on:
  workflow_dispatch:
  schedule:
    - cron: '6 9 * * *' # Run daily

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Checkout rc branch for committing
        run: |
          git fetch origin rc
          git checkout rc
          git checkout main -- foundry-bin/update.sh
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Building package
        run: 'cd ./foundry-bin && ./update.sh rc'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: rc
          commit_message: 'foundry-bin/releases.nix: rc update'
          commit_author: Nix Updater <actions@github.com>
