name: Update foundry-bin monthly

on:
  workflow_dispatch:
  schedule:
    - cron: '6 9 * * *' # Run daily, the monthly release detection should be idempotent

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: monthly
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Building package
        run: 'cd ./foundry-bin && ./update_nightly.sh monthly'
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: monthly
          commit_message: 'foundry-bin/releases.nix: Nightly update for monthly branch'
          commit_author: Nix Updater <actions@github.com>
